apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master
  namespace: argocd
spec:
  destination:
    namespace: hello-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/base
    repoURL: 'https://github.com/shashank0202/argo-kustomize.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false