apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespacetobereplaced
spec:
  destination:
    namespace: namespacetobereplaced
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/base
    repoURL: 'https://github.com/shashank0202/argo-kustomize.git'
    targetRevision: feat/namespacetobereplaced
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false