apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dddd
spec:
  destination:
    namespace: ${GITHUB_REF##*/}
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/base
    repoURL: 'https://github.com/shashank0202/argo-kustomize.git'
    targetRevision: feat/${GITHUB_REF##*/}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false