apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: 1ed2280a17189332fe84dcaba40b1035c89bf439
