apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: ${GITHUB_REF##*/}
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: 04f3e7437574a2002bdc2b4168f7ac05724bc000
