apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: namespacetobereplaced
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: 766fb089d71985167eea2412edc552fe55e43e51
