apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: dddd
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: ed3f82c2dba3c96c239a7ba7fbcd4bcf75c8f6b3
