apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: snk0202/hello-gitops
  newTag: a752b35049b71b4ad89c5c1ccb08ace6f5398711
